import 'package:flutter/material.dart';
import '../../../../app/constants/app_colors.dart';
import '../../../../app/constants/app_sizes.dart';
import '../../../../app/dependency_injection/service_locator.dart';
import '../../../../core/extensions/context_extensions.dart';
import '../../../../core/widgets/app_primary_button.dart';
import '../../../../core/widgets/app_text_field.dart';
import '../../domain/entities/meeting.dart';
import '../../domain/repositories/meeting_repository.dart';
import '../../../../core/utils/enums.dart';

class ScheduleMeetingSheet extends StatefulWidget {
  const ScheduleMeetingSheet({
    super.key,
    required this.targetId,
    required this.targetName,
    this.targetAvatar,
  });

  final String targetId;
  final String targetName;
  final String? targetAvatar;

  static Future<bool?> show(
    BuildContext context, {
    required String targetId,
    required String targetName,
    String? targetAvatar,
  }) {
    return showModalBottomSheet<bool>(
      context: context,
      showDragHandle: true,
      isScrollControlled: true,
      backgroundColor: Theme.of(context).colorScheme.surface,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(AppSizes.radiusXl),
        ),
      ),
      builder: (_) => Padding(
        padding: EdgeInsets.only(
          bottom: MediaQuery.of(context).viewInsets.bottom,
        ),
        child: ScheduleMeetingSheet(
          targetId: targetId,
          targetName: targetName,
          targetAvatar: targetAvatar,
        ),
      ),
    );
  }

  @override
  State<ScheduleMeetingSheet> createState() => _ScheduleMeetingSheetState();
}

class _ScheduleMeetingSheetState extends State<ScheduleMeetingSheet> {
  final _titleCtrl = TextEditingController(text: 'Introduction Meeting');
  final _meetingUrlCtrl = TextEditingController();
  final _agendaCtrl = TextEditingController();
  DateTime? _selectedDate;
  TimeOfDay? _selectedTime;
  final int _durationMinutes = 30;
  bool _isLoading = false;

  Future<void> _pickDate() async {
    final date = await showDatePicker(
      context: context,
      initialDate: DateTime.now().add(const Duration(days: 1)),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (date != null) {
      setState(() => _selectedDate = date);
    }
  }

  Future<void> _pickTime() async {
    final time = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );
    if (time != null) {
      setState(() => _selectedTime = time);
    }
  }

  Future<void> _schedule() async {
    final title = _titleCtrl.text.trim();
    if (title.isEmpty) {
      context.showSnack('Please enter a meeting title', isError: true);
      return;
    }
    if (_selectedDate == null || _selectedTime == null) {
      context.showSnack('Please select a date and time', isError: true);
      return;
    }
    final meetingUrl = _meetingUrlCtrl.text.trim();
    if (meetingUrl.isEmpty) {
      context.showSnack('Please enter a meeting URL', isError: true);
      return;
    }

    setState(() => _isLoading = true);

    final startTime = DateTime(
      _selectedDate!.year,
      _selectedDate!.month,
      _selectedDate!.day,
      _selectedTime!.hour,
      _selectedTime!.minute,
    );

    final meeting = Meeting(
      id: '', // Generated by backend
      title: title,
      withName: widget.targetName,
      withId: widget.targetId,
      withAvatar: widget.targetAvatar,
      startTime: startTime,
      durationMinutes: _durationMinutes,
      status: EntityStatus.pending,
      meetingLink: meetingUrl,
      agenda: _agendaCtrl.text.trim(),
      participants: [widget.targetId],
    );

    final res = await sl<MeetingRepository>().schedule(meeting);

    if (mounted) {
      setState(() => _isLoading = false);
      res.fold((f) => context.showSnack(f.message, isError: true), (success) {
        context.showSnack('Meeting scheduled with ${widget.targetName}!');
        Navigator.of(context).pop(true);
      });
    }
  }

  @override
  void dispose() {
    _titleCtrl.dispose();
    _meetingUrlCtrl.dispose();
    _agendaCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(
          AppSizes.xl,
          0,
          AppSizes.xl,
          AppSizes.xxxl,
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Schedule Meeting',
                        style: context.text.headlineSmall?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      Text(
                        'with ${widget.targetName}',
                        style: context.text.bodyMedium?.copyWith(
                          color: AppColors.subtleText,
                        ),
                      ),
                    ],
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.close_rounded),
                  onPressed: () => Navigator.of(context).pop(),
                ),
              ],
            ),
            AppSizes.vGapXl,
            AppTextField(
              controller: _titleCtrl,
              label: 'Meeting Title',
              hint: 'e.g. Introduction & Synergy',
            ),
            AppSizes.vGapLg,
            Row(
              children: [
                Expanded(
                  child: InkWell(
                    onTap: _pickDate,
                    borderRadius: BorderRadius.circular(AppSizes.radiusMd),
                    child: Container(
                      padding: const EdgeInsets.all(AppSizes.md),
                      decoration: BoxDecoration(
                        border: Border.all(color: AppColors.border),
                        borderRadius: BorderRadius.circular(AppSizes.radiusMd),
                      ),
                      child: Row(
                        children: [
                          const Icon(
                            Icons.calendar_today_rounded,
                            size: 20,
                            color: AppColors.primary,
                          ),
                          AppSizes.hGapMd,
                          Expanded(
                            child: Text(
                              _selectedDate == null
                                  ? 'Select Date'
                                  : '${_selectedDate!.day}/${_selectedDate!.month}/${_selectedDate!.year}',
                              style: context.text.bodyMedium,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
                AppSizes.hGapMd,
                Expanded(
                  child: InkWell(
                    onTap: _pickTime,
                    borderRadius: BorderRadius.circular(AppSizes.radiusMd),
                    child: Container(
                      padding: const EdgeInsets.all(AppSizes.md),
                      decoration: BoxDecoration(
                        border: Border.all(color: AppColors.border),
                        borderRadius: BorderRadius.circular(AppSizes.radiusMd),
                      ),
                      child: Row(
                        children: [
                          const Icon(
                            Icons.access_time_rounded,
                            size: 20,
                            color: AppColors.primary,
                          ),
                          AppSizes.hGapMd,
                          Expanded(
                            child: Text(
                              _selectedTime == null
                                  ? 'Select Time'
                                  : _selectedTime!.format(context),
                              style: context.text.bodyMedium,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            ),

            AppSizes.vGapLg,
            AppTextField(
              controller: _meetingUrlCtrl,
              label: 'Meeting URL *',
              hint: 'Enter Meeting URL',
              prefixIcon: Icons.link_rounded,
              keyboardType: TextInputType.url,
              textInputAction: TextInputAction.next,
            ),
            AppSizes.vGapLg,
            AppTextField(
              controller: _agendaCtrl,
              label: 'Agenda / Notes (Optional)',
              hint: 'Briefly describe what you want to discuss.',
              maxLines: 3,
            ),
            AppSizes.vGapXl,
            AppPrimaryButton(
              label: 'Schedule Meeting',
              icon: Icons.send_rounded,
              isLoading: _isLoading,
              onPressed: _schedule,
            ),
          ],
        ),
      ),
    );
  }
}
