// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXmwelS8HTvXXdQsGuc8nVsMkvYmxoJQc',
    appId: '1:817575811603:web:0cbfb1883a6f0af240bde6',
    messagingSenderId: '817575811603',
    projectId: 'goexperts-a979c',
    authDomain: 'goexperts-a979c.firebaseapp.com',
    storageBucket: 'goexperts-a979c.firebasestorage.app',
    measurementId: 'G-889Q23QX6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7odh9Q-Ib7536u52V6gyIAQXE9LC7xTM',
    appId: '1:817575811603:android:b12759511ee75ba840bde6',
    messagingSenderId: '817575811603',
    projectId: 'goexperts-a979c',
    storageBucket: 'goexperts-a979c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC32Vz4_1aPaKZee2Cu2ohjwBS3m22qnV4',
    appId: '1:817575811603:ios:5cd59d9e41334d2540bde6',
    messagingSenderId: '817575811603',
    projectId: 'goexperts-a979c',
    storageBucket: 'goexperts-a979c.firebasestorage.app',
    androidClientId:
        '817575811603-m2jfe6l1lunbiunjvmlrilj7p6ig25kt.apps.googleusercontent.com',
    iosClientId:
        '817575811603-7pgbim1pbp6ps0h89594hnh9kouj2jgc.apps.googleusercontent.com',
    iosBundleId: 'com.doorstephub.goexperts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC32Vz4_1aPaKZee2Cu2ohjwBS3m22qnV4',
    appId: '1:817575811603:ios:5cd59d9e41334d2540bde6',
    messagingSenderId: '817575811603',
    projectId: 'goexperts-a979c',
    storageBucket: 'goexperts-a979c.firebasestorage.app',
    androidClientId:
        '817575811603-m2jfe6l1lunbiunjvmlrilj7p6ig25kt.apps.googleusercontent.com',
    iosClientId:
        '817575811603-7pgbim1pbp6ps0h89594hnh9kouj2jgc.apps.googleusercontent.com',
    iosBundleId: 'com.doorstephub.goexperts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXmwelS8HTvXXdQsGuc8nVsMkvYmxoJQc',
    appId: '1:817575811603:web:e7cc7dc07caad9ba40bde6',
    messagingSenderId: '817575811603',
    projectId: 'goexperts-a979c',
    authDomain: 'goexperts-a979c.firebaseapp.com',
    storageBucket: 'goexperts-a979c.firebasestorage.app',
    measurementId: 'G-CRHP3P4HLM',
  );
}
